### ISSUE TITLE
Attn_map versus box_labels

### ISSUE THREAD

**Issue by Leo-Repo** [NUSTM/ITM#1]
https://github.com/NUSTM/ITM/blob/86684054fbd33f0425583acf37d632fbd021c6c0/model.py#L134
Although it is a problem of comparing probability distributions, are their position distributions really aligned?

**Comment by Miss-Ming** [comment]
In our experiment, we first use Faster-RCNN to extract the top-100 objects based on the predicted confidence of each object, and the 100 object sequence is ranked based on their predicted confidences. Next,  given the object sequence, we compute the iou scores of each object in the sequence respect to the ground truth bounding box as the box_labels. For our model, the same object sequence was used for the model input and the inter-modal interaction to obtain Attn_map. Thus, the positions of box_labels and Attn_map are aligned.

**Comment by Leo-Repo** [comment]
I see, thanks for your reply！
