### ISSUE TITLE
Can't locate FasterRCNN extract_feature.py

### ISSUE THREAD

**Issue by ipheiman** [NUSTM/ITM#3]
Hi authors, thank you for the impressive work! I am very excited to try this out.

I am following the instructions to run the model and i can't find this "python ./tools/extract_feat.py" in the FasterRCNN link provided. Could you advise on this?

Thanks!

**Comment by Miss-Ming** [comment]
I'm sorry for missing the file of image feature extraction, which has been uploaded to the directory [https://github.com/NUSTM/ITM/blob/main/extract_feat.py](https://github.com/NUSTM/ITM/blob/main/extract_feat.py)

**Comment by ipheiman** [comment]
Hi @Miss-Ming , thank you for uploading the file! Can I check where to find experiments/cfgs/faster_rcnn_end2end_resnet_vg.yml ? I can only find experiments/cfgs/faster_rcnn_end2end_resnet.yml in here : https://github.com/peteanderson80/bottom-up-attention/tree/master/experiments/cfgs

Thanks!

**Comment by Miss-Ming** [comment]
Hi @ipheiman , these two files are the same.

**Comment by ipheiman** [comment]
Hi @Miss-Ming , Thanks for updating the readme and clarifying my doubts. I managed to extract the region features for my custom dataset. Greatly appreciated your help, will close the issue now.
