### ISSUE TITLE
question about filter matrix (gate)

### ISSUE THREAD

**Issue by Leo-Repo** [NUSTM/ITM#4]
https://github.com/NUSTM/ITM/blob/01e298d8770d4ba4dc18b020896dcded23e4b91c/model.py#L120
Hi, author,
There, every target-based image representation (sentence_aware_image, [batch_size, 100, 768]) multiply a corresponding filter matrix (gate, [batch_size, 100, 768]), but the filter matrix's all number is equal to the same value (relevant score with range of [0,1]). So, how can I understand it can alleviate the noise from unrelated images? In other words, this module is only valid if it is equal to 0, right?
Many thanks!

**Comment by Miss-Ming** [comment]
No,  when the correlation between the image and the entity is low, much less visual features
are weighted to the linguistic features, resulting in an even distribution of attention (as in the first two cases in Table 7),  and a small proportion of the emotional decision.

**Comment by Leo-Repo** [comment]
How indeed it is an elaborate model! Thanks for your reply!
